noblox/noblox.js

lib/user/onBlurbChange.js
settings.json

Event that fires whenever specified user's blurb is updated.

Add `onBlurbChange` event

---

README.md

Add login workaround docs

---

lib/group/getPlayers.js
lib/group/post.js

Fixed post.js using the new [API](https://groups.roblox.com/docs#!/Wall/post_v2_groups_groupId_wall_posts).

Fixed post.js and getPlayers.js using API

---

lib/user/follow.js

When this function has an error with an error message, provide more details by adding the error message.

Provide more error details

---

.gitignore
package-lock.json
package.json
typings/index.d.ts

*This pull request includes updating npm dependencies*
Implemented TypeScript declarations for:
- Asset
- Avatar
- Chat
- Game
- Group
- Party
- User
- Util
These include event emitters and interfaces needed for the functions (including CookieJar).

Added TypeScript declaration

---

lib/user/follow.js

Revert "Provide more error details"

---

typings/index.d.ts

I took a decent look at the actual functions within the directories and i used a couple of context clues to fix these minor problems. The getFriendRequests thing for sure is a typo.

Attempt to fix some typings in declaration file

---

lib/group/getWall.js
lib/group/onAuditLog.js
typings/index.d.ts

Support for tracking audit log updates. Functions like all the other group events.

Implement onAuditLog and fix getWall

---

lib/group/getAuditLog.js
lib/group/getPlayers.js
lib/group/getShout.js
lib/group/getWall.js
lib/user/getBlurb.js
lib/user/getFriendRequests.js
lib/user/getMessages.js
package-lock.json
package.json
typings/index.d.ts

When we moved to let/const one of the side effects was that overriding "Promise" with the Bluebird implementation no longer applied accross all files.
Closes #172 
This PR imports bluebird in the required files. We may want to import bluebird in all files - or move fully to async await in future?

Fix events

---

examples/revertRanks.js
lib/game/getPlaceInfo.js
typings/index.d.ts

Lets people get data on a game. Useful for game developers who want to see how many likes, dislikes, visit count, favourites, and how many people are in game currently.
Usage:
`<noblox>.getPlaceInfo(placeId)`
(this is my first pull request so idk what im doing)

Add getPlaceInfo()

---

lib/util/refreshCookie.js

Remove the requestVerificationToken from /signoutfromallsessionsandreauthenticate as it was removed by Roblox.

Remove requestVerificationToken

---

lib/user/getPlayerInfo.js
typings/index.d.ts

I have tested this on my side and I got it to work. I just thought this would be a cool idea for people getting player info

Add pastUsernames to getPlayerInfo

---

lib/asset/buy.js
lib/asset/configureItem.js

Update the endpoints as the old ones are deleted. Fixed with Standard JS.

Fix configuring assets and buying them.

---

index.html

Started adding side tabs for events and updated the top to mention stuff about refreshing cookies. Planning to go back through and make additional changes to that, as well as actually build the pages for the side tabs. Have not pushed them in this PR because someone else might want to also help make those pages.

gh-pages update

---

index.html

Reverts suufi/noblox.js#199
This messed up the GH pages.
A good example of why we need automated deployment for better testing.

Revert "gh-pages update"

---

lib/badges/getAwardedTimestamps.js
lib/badges/getUserBadgeTimestamp.js
typings/index.d.ts

This feature uses the https://badges.roblox.com/docs#!/BadgeAwards/get_v1_users_userId_badges_awarded_dates api
It allows you to see the timestamp of when a user is awarded a badge.

Add getUserBadgeTimestamp

---

lib/presence/getPresences.js

Uh I know I only removed one line but...

Remove unnecessary console.log()

---

lib/user/getPlayerInfo.js
typings/index.d.ts

Adds friendcount, followingcount, and followercount to the function.

Add more features to getplayerinfo

---

typings/index.d.ts

Add index typing for IGroupPartial

---

lib/user/getPlayerInfo.js
lib/util/getPageResults.js
package.json
test/user.test.js
typings/index.d.ts
typings/jsDocs.ts

Fixed getPlayerInfo, updated typings, and made it consistent with the rest of the library.

Fix getPlayerInfo

---

lib/game/getPlaceInfo.js
typings/index.d.ts

Fixes #259 by adding support for an optional `jar` parameter.

Update getPlaceInfo() to use cookie.

---

typings/index.d.ts

Fixed the following typescript error by providing the argument 'any' to Array Type:
`Generic type 'Array<T>' requires 1 type argument(s)`

Updated index.d.ts

---

typings/index.d.ts

Updated the return type of `getCollectibles` in typings to match with the actual return type

Updated return type of `getCollectibles` function

---

typings/index.d.ts

• Updated getInventory return type to array of InventoryEntry
• Updated getInventoryByID return type to array of InventoryEntry
• Removed unused Inventory interface

Fixed Error in Typings

---

README.md
package.json
tutorials/Authentication.md

Increment version for release, revise some docs around authentication, namely:
- Remove refresh cookie warning
- Add a warning about CSRF Cookie errors and improper setCookie usage, since that seems to come up a lot

v4.8.4, Documentation updates

---

typings/index.d.ts

Replaced `ThumbnailSizes` to `HeadshotSizes` for method `getPlayerThumbnail`

Fixed typings issue

---

lib/user/canManage.js
test/user.test.js
typings/index.d.ts

Closes issue #276.
A basic function with a test case implemented.

Implement canManage()

---

lib/asset/configureItem.js
lib/asset/deleteFromInventory.js

Documented and validated `deleteFromInventory()`.
Fixed casing and optional status of `sellForRobux` in `configureItem()`:

Document deleteFromInventory, configureItem parameters

---

.github/workflows/npmpublish.yml
package.json
yarn.lock

This should automatically release PRs if assigned the release tag w/ proper versioning.

Implement auto release

---

lib/user/getPlayerBadges.js
test/user.test.js
typings/index.d.ts
typings/jsDocs.ts

Add some documented displayName usages to typings. 
Related to #373  but will not close it as there will be more undocumented usages.

Typings updates - Add displayName

---

typings/index.d.ts

Update typescript typing for Friends

---

typings/index.d.ts
typings/jsDocs.ts

API returns presenceType, why not add it to typings?

add presenceType to FriendEntry

---

examples/cleanPlayers.js
examples/savePlayers.js

Fixed the error caused by roleset being a missing required argument.

fixed savePlayers.js example

---

lib/user/getCollectibles.js
lib/user/getPlayerBadges.js
typings/index.d.ts

- Update getPlayerBadges for developers to easily retrieve fully user badges 
- Fix getCollectibles outdated documentation at line 17.

Implement getPlayerBadges paginations

---

lib/asset/deleteFromInventory.js
lib/game/getGamePasses.js

This will fix categories and put them in the correct spot for the gh-page documentation

Fix categories

---

lib/group/setGroupDescription.js
lib/group/setGroupName.js
typings/index.d.ts
typings/jsDocs.ts

Add setGroupDescription and setGroupName. These are clones of shout - I intend to reduce the amount of duplicate code here in a future version when we move to a different http library and centralise a lot of code.
Implements #461

Add setGroupDescription and setGroupName

---

lib/group/deleteWallPostsByUser.js
typings/index.d.ts

Closes #591 
This pull request will add the `deleteWallPostsByUser` method unto the group module.

Add `deleteWallPostsByUser.js`

---

typings/index.d.ts
typings/jsDocs.ts

FriendRequest is a number, not an object containing a number

Fix FriendRequest type

---

lib/user/setCookie.js
lib/util/getCurrentUser.js

Fixes drafts requested in #579

Draft fixes for #579

---

lib/game/addDeveloperProduct.js

Fix addDeveloperProduct.js

---

typings/index.d.ts

Correctly use number for userId

---

tutorials/Authentication.md
tutorials/Event Emitters.md
tutorials/Promises.md

Append 'javascript' to code block markdown in tutorials

---

lib/games/addDeveloperProduct.js

Changed to use another endpoint, as the previous one was returning a 404 error.

Fix addDeveloperProduct

---

lib/games/addDeveloperProduct.js

When using the new api, it returns a completely different id. I can then use that id to grab the real product id using a GET api.

Fix addDeveloperProduct not returning a product id

---

lib/client/onNotification.js

Standard was screaming about it when running `npm run lint`

Fix linting in onNotification

---

lib/util/http.js
lib/util/jar.js
package.json

https://github.com/noblox/noblox.js/issues/143#issuecomment-2169316823
Seems to have passed the same tests as well.

Upgrade to maintained fork of request

---

typings/index.d.ts

Seems like this was missed when adding this function

Add getAuthenticatedUser typing

---

lib/asset/deleteFromInventory.js

Update endpoint for deleteFromInventory

---

lib/users/getUserInfo.js

Updated the getUserInfo function to handle arguments correctly.
Very simple fix and a small change, however I did spend longer than I'd like to admit debugging it 😅

Fix getUserInfo

---

lib/accountsettings/block.js
lib/accountsettings/unblock.js

fix: Update user block/unblock endpoints

---

lib/util/http.js
settings.json
typings/index.d.ts
typings/jsDocs.ts

Not really a fix but not exactly a feature either

fix: Update user agent per Roblox's request
