noblox/noblox.js

- lib/util/http.js
New APIs have a different status message.
This should address #23
> Retrieve XCSRF for newer APIs

- lib/user/cookieLogin.js
- lib/util/relog.js
This new method makes use of Froast's relog function. It's to bypass the login captcha introduced by Roblox recently.
How to use:
- Login to your bot account manually
- Open inspect element (if it's chrome, Control + Shift + i)
- Click "Application"
- Click "Cookies"
- Copy .roblosecurity and run cookieLogin with it
All other sessions for that account will be invalidated and a new token will be stored internally.
After this, all you need to do is run cookieLogin with no parameters. Tokens will be automatically regenerated once a day. Any params will be ignored unless the internal cookie file is out of date.
> Add cookieLogin bypass

- lib/group/shout.js
Redid shout.js using the new [Group Shout API](https://groups.roblox.com/docs#!/Groups/patch_v1_groups_groupId_status).
> Fixed shout.js using new API

- lib/group/exile.js
Opening a new pull request because the previous one was accidentally closed by me.
So, it seems like the current exile.js doesn't work when it gets an error. It always returns "Cannot read property length of undefined".
I added a JSON.parse() to parse the string, and it seems to work now.
> Fix for exile.js

- lib/group/shout.js
Not sure whats going on here, but shout has an unnessesary JSON.parse which is causing an error.
Res.body is already an object, not a string.
Simple fix!
> Fix shout (Remove JSON.parse)

- lib/group/shout.js
The module throws an error when trying to shout.
```
Unhandled rejection SyntaxError: Unexpected token o in JSON at position 1
```
This can be fixed by simply removing the JSON.parse on lines 29 & 31.
> Fix unnecessary JSON.parse at lines 29 & 31

- README.md
The current link is linking to the github wiki, documentation is located here: https://noblox.js.org/.
This may have been intentional, if so, just close it.
> Added noblox.js.org for the documentation link

- lib/group/getGroupTransactions.js
- lib/group/getPlayers.js
- lib/user/getUserTransactions.js
- typings/index.d.ts
These endpoints return the list of items sold by a group or user. Will be useful for searching through sales to find or analyse them. The user endpoint can only be used for the currently authenticated user - I pointed out in the commit that it may be best to just use the userId of the said user.
May also be useful to have an onSale/onPurchase event for groups and user. If anyone wants to do that, go ahead. I might if I find time, but I don't specifically need these events at the moment.
Yes, this PR is pretty much just copypasta but I'd like access to these endpoints without using a fork of noblox.
> Add "get transactions" endpoints & update getPlayers

- lib/user/getUserTransactions.js
I forgot to make the parent function async when awaiting on getCurrentUser. I made the modification without thought or testing, which was clearly a bad idea as it broke the entire thing!
> Fix await in non-async function

- lib/user/getGroups.js
- lib/util/getGeneralToken.js
- package-lock.json
- package.json
See docs: https://auth.roblox.com/docs#!/v2
Tested with the following:
```js
const no = require("./noblox.js");
async function test () {
await no.setCookie("Cookie");
try {
const t = await no.getGeneralToken()
console.log(`Token, `, t);
} catch (e) {
console.error(`Failed: `, e);
}
}
test();
```
Closes #163
> v4.6.3: Fix getCurrentToken (Move to v2)

- typings/index.d.ts
Added two missing methods (user/setCookie and util/refreshCookie added in v4.6.0) to the typings file.
- The logic shown with setCookie describes a pattern in which the return types are conditional based on the parameters. By default a `Promise<LoggedInUserData>` is returned, however if the optional parameter `shouldValidate` is set to false then TypeScript infers the method response type will be a boolean.
| Arguments | Inferred type |
| ------------- | ------------- |
| `setCookie("*")`  | `Promise<LoggedInUserData>`  |
| `setCookie("*", true)`  | `Promise<LoggedInUserData>`  |
| `setCookie("*", false)`  | `boolean`  |
> Add "setCookie" and "refreshCookie" declarations.

- lib/group/setRank.js
Adds a new error if you try to pass a rank number as a string.
I originally considered just converting it but you shouldn't be passing rank numbers as strings, so this just makes it more clear whats wrong.
Closes #175
> Error for non-number 

- index.html
The GetStatus documentation reads as:
```
Get Status
This function returns the blurb of a user. The blurb is the equivalent of the user's description on Roblox, not their status message.
```
It should say:
```
Get Status
This function returns the status of a user. The blurb is the equivalent of the user's description on Roblox, not their status message.
```
> Fix GetStatus typo

- lib/game/configureGamePass.js
- test/game.test.js
- typings/index.d.ts
- typings/jsDocs.ts
I added a `configureGamePass()` method since the existing `configureItem()` is incompatible with GamePassIDs, as GamePassIDs can overlap AssetIDs. 
I tried to maintain parity with the structure used by `configureItem()` as much as possible, but the `www.roblox.com/game-pass/update/` endpoint forces weird behavior as it is seemingly designed for the web browser rather than a REST API.
My method takes the parameters:
```js
configureGamePass(gamepassId: number, name: string, description?: string, price?: number | boolean, jar?: CookieJar)
```
Roblox breaks the dashboard up into `name`/`description` and `price`/`isForSale`; you cannot change both groups with a singular API call, ergo the WET code that makes up to two API calls; unnecessary calls are automatically dropped. Passing `0`, `false` …
> Added configureGamePass() method.

- lib/index.js
Fix bad reference that causes warnings when used with TypeScript
This isn't really important, since JS *manages*, but it's nice and will get rid of annoying warnings from my runtime.
The warning was: 
``(node:1572) Warning: Accessing non-existent property 'func' of module exports inside circular dependency``
> Update index.js to fix accessing of non-existent property

- lib/user/getMessages.js
- lib/user/getOwnership.js
- test/user.test.js
- typings/index.d.ts
Currently `getOwnership()` only supports assetIDs; I changed the endpoint being used so it now supports an optional parameter for the alternative item types: `GamePass`, `Badge`, and `Bundle`.
All changes should maintain backwards compatibility. I also added three unit tests using [`Qxest`](https://www.roblox.com/users/55549140/profile) which covers the three additional ID types.
---
Minor documentation hotfixes to `getMessages()` and `configureGamePass()` for parity are included as well.
> Update getOwnership() to support game passes, badges, and bundles.

- lib/asset/uploadModel.js
A fix regarding the `uploadModel()` endpoint to address the new X-CSRF-Token requirement [per the DevForum announcement](https://devforum.roblox.com/t/changes-to-the-data-upload-ashx-endpoint-x-csrf-token-validation/1021830).
> Use X-CSRF-Token to reflect endpoint change

- typings/index.d.ts
The post method was removed in 4.6.1 due to captchas. It is still in the typings.
> Remove post method from typings

- lib/user/getPremium.js
- lib/user/getPremiumStatus.js
- typings/index.d.ts
Added a new function `getPremium()` that takes a user id, and returns `true` or `false` depending on whether the user with the given userId has premium or not. This uses the following endpoint:
`https://premiumfeatures.roblox.com/v1/users/${userId}/validate-membership`
This endpoint requires the bot to be logged in.
Feel free to user a better name than `getPremium`.
`// login with cookie`
`const hasPremium = await noblox.getPremium(123456)`
> Added getPremium() function

- lib/user/getGroups.js
The endpoint `https://groups.roblox.com/v1/users/${userId}/groups/primary/role` returns `null` when the user has no primary group selected. 
The previous code did not require the response to exist and thus threw `UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'group' of null` when running `getGroups()` on a user with no groups or no primary group selected. This change fixes the issue, and causes `[]` to return when the user has no group, and `isPrimary: false` for all objects if the user is in multiple groups, but no group is primary.
Optional chaining was not used to preserve backwards compatibility.
**Example UserID:** `2416399685`
Before:
After:
> Fixes getGroups() cannot read property of null typeError.

- lib/user/getGroups.js
- lib/user/getPlayerInfo.js
- package.json
Replaces all `Promise.allSettled()` usage with `Promise.all()` and `.map()` as referenced by (#283). In turn, this should remove the `node >=12.9.0` requirement added by #254.
I have tested on `node 11.15.0` with regard to the changed methods, `getPlayerInfo()` and `getGroups()`.
I cannot comment in regard to other incompatibilities that may have been introduced outside of `promise.allSettled()`.
> Remove promise.allSettled and 12.9.0 dependency added by (#254)

- lib/user/getUserTransactions.js
- typings/index.d.ts
`getUserTransactions()` is using a removed endpoint; updating to `v2` fixes it; also corrected the code example for JSDocs. Appears to be an unbreaking change.
JSDocs had example usage providing a `userId` which isn't reflected in `index.d.ts`, the endpoint only works on the authenticated users so it is now removed from documentation.
Thank Jullian's ranting for the undocumented solution.
> Update getUserTransactions() endpoint version and code example

- lib/group/getGroupFunds.js
- test/group.test.js
- typings/index.d.ts
Returns the amount of robux available in group funds for a given group. A test case is included.
Valid use cases can include making notifiers for when a group reaches 100,000R for DevEx or visualizing profits over time. Added by request in the `noblox.js` Discord.
---
There were discussions in the past about avoiding this endpoint because it could be used for abuse with `groupPayout()`; but in retrospect, people can already do a 100% group payout without this endpoint.
https://github.com/suufi/noblox.js/blob/0ee12320bb998475ac320082a0a1681d282688bf/lib/group/groupPayout.js#L18
https://github.com/suufi/noblox.js/blob/0ee12320bb998475ac320082a0a1681d282688bf/lib/group/groupPayout.js#L85
> Implement getGroupFunds()

- lib/user/getPlayerThumbnail.js
JSDocs information is above variables instead of the function so documentation lists the method as a const member. This _should_ fix that. Thanks to @popeeyy for the potential solution.
> Fix getPlayerThumbnail() documentation

- lib/user/unblock.js
I have seen a case where the error message is returned as a string in body.error.
I have added this as an OR to make sure if Roblox sometimes returns the error as body.message, these are not missed.
> Fix unblock error message

- lib/asset/uploadItem.js
Code example incorrectly uses `upload()` instead of `uploadItem()`. I also made a [hyperlink to the Developer Wiki for a list of AssetType enums](https://developer.roblox.com/en-us/api-reference/enum/AssetType).
https://github.com/suufi/noblox.js/blob/5137e625223bf9dba27c83e0ad089e49e95e0f1c/lib/asset/uploadItem.js#L22
> Fix uploadItem() code example

- examples/cleanPlayers.js
- examples/savePlayers.js
- lib/group/changeRank.js
- lib/group/getRole.js
- lib/group/getRoles.js
- lib/group/setRank.js
Not sure why we convert role.id to role.ID? I imagine it was in favour of past consistency.
The typings show role has an `id` field, not `ID`. This is not the case.
This brings the library in-line with the typings, but retains backwards compatibility.
> Remove Role.ID in favour of role.id

- examples/revertRanks.js
Fixes the `revertRanks.js` example snippet was broken by https://github.com/suufi/noblox.js/commit/8e4701d1b36aa1ed71d5b6c9aefa8d6c3d184190, which changed the field name `roleset` to `rank`.
Tested using the noblox.js group, and one of my private groups.
> Fix revertRanks.js example

- lib/group/getGroupGames.js
- test/group.test.js
- typings/index.d.ts
- typings/jsDocs.ts
**This is a duplicated fork of #312, but has a readable commit/file history, and has some logic errors fixed.**
~~**NOTE:** A test case was added, but currently it has to point to one of my test groups instead of `noblox.js` as some reason all new games I try to create become personal games instead of group games.. possibly a symptom of their experience/game rushed rebranding.~~ Test now uses the `noblox.js` test group.
Screenshot of the function working:
> Implement getGroupGames()

- lib/group/getGroupRevenueSummary.js
- typings/index.d.ts
- typings/jsDocs.ts
Closes issue #333.
I have omitted a Jest test case since the method requires `Spend group funds` permissions which cannot be given to Guest users.
Default `timeFrame` is set to `Month`, as Robux takes two weeks to pend, thus `Month` is the most likely to be used.
> Implement getGroupRevenueSummary()

- lib/game/getGameSocialLinks.js
- lib/group/getGroupRevenueSummary.js
- lib/group/getGroupSocialLinks.js
- lib/user/getPlayerThumbnail.js
- lib/user/getUserSocialLinks.js
- test/game.test.js
- test/group.test.js
- test/user.test.js
- typings/index.d.ts
- typings/jsDocs.ts
Closes issue #359.
Implements `getUserSocialLinks()`, `getGameSocialLinks()`, and `getGroupSocialLinks()`, with Jest test cases. I opted against the issue's requested name, `getUserPromotionChannels()` so it has parity with the naming scheme used on the website and companion methods.
**Test Cases using noblox.js group/account:**
> Implement social link endpoints.

- lib/user/getPlayerInfo.js
The commit https://github.com/noblox/noblox.js/commit/31de328d70e970d2a9f8f30c41b62d2027ecad50 added `displayName` to the typing of `PlayerInfo` but never added the functionality. This fixes that.
> Add displayNames support to getPlayerInfo()

- README.md
- lib/asset/getResaleData.js
- lib/asset/getResellers.js
- test/asset.test.js
- typings/index.d.ts
- typings/jsDocs.ts
Closes issue #298.
Adds `getResaleData()` and `getResellers()` with unit tests.
**Unit Tests:**
---
**getResaleData():**
**getResellers():**
> Implement resale endpoints

- lib/group/shout.js
The method [`shout()`](https://noblox.js.org/global.html#shout) states `message` is an optional parameter that defaults to `""`.
Currently, `message` gets passed as `undefined`, causing an error to be thrown by the API- this fixes that while maintaining backwards compatibility.
```js
noblox.shout(9997719)
```
**OLD:**
**NEW:**
> Fix clear shout optional parameter

- lib/util/getCurrentUser.js
- lib/util/http.js
To overload `jar`, you need to pass an object `{ session: 'COOKIE' }`, this is not intuitive and results in over complicated looking code.
```js
await noblox.getCurrentUser({ jar: { session: 'COOKIE' } })
// is now equivalent to
await noblox.getCurrentUser({ jar: 'COOKIE' })
```
This pull request removes the need for the session object, enabling a cookie string to be passed instead of the wrapper object- **backwards compatibility is maintained.**
---
`string` and `object (str)` highlight the new functionality
> Simplify jar overloading by permitting string inputs

- lib/game/updateUniverseAccess.js
- typings/index.d.ts
Sets the universe root place to private or public.
This was a requested method via the noblox.js support server; this method can be used by developers to automatically open and close their game for a beta weekend without needing to stay up late/wake up early to manually lock their game.
I have omitted test cases do to their reliance on internal cookies; likewise since the success state returns `{}`, an [additional method would needed](https://games.roblox.com/docs#!/Games/get_v1_games_multiget_playability_status) to be implemented to validate if the target universe changed it's access settings.
> Implement updateUniverseAccess()

- lib/group/searchGroups.js
- lib/util/getPageResults.js
- test/group.test.js
- typings/index.d.ts
- typings/jsDocs.ts
> Implement searchGroups

- lib/asset/getResellers.js
- lib/game/getGamePasses.js
- test/game.test.js
- typings/index.d.ts
- typings/jsDocs.ts
Adds `getGamePasses` and passes `jar` in `getResellers` for cookie overloading support.
Closes issue #400.
> Implement getGamePasses and fix getResellers jar param

- lib/group/getGroupTransactions.js
- lib/user/getUserTransactions.js
- typings/index.d.ts
- typings/jsDocs.ts
Current getGroupTransactions is not working with the cursor parameter but bumping it up to v2 solves the issue. Roblox is now using this by default.
Everything remains the same except for the URL.
> Bumped the getGroupTransactions url to v2

- lib/avatar/setAvatarBodyColors.js
Someone accidently put/forgot to remove "Colours"
Resolves #506
> Fix documentation spelling (Colours -> Colors)

- lib/group/onGroupTransaction.js
- lib/util/getPageResults.js
- getPageResults must use Bluebird to expose Promise.timeout: Used for all shortPoll events.
- Breaking changes were merged to getGroupTransactions without updating dependent methods. My bad! I approved it.
In future we should consider:
- Improving/working on shortPoll - it can be a bit flimsy
- Getting rid of Bluebird - we mostly use Promise.timeout and it's not really needed now - native promises are a lot better than they used to be. We could drop a dependency reasonably easily.
> Fix onGroupTransaction and make getPageResults use bluebird

- lib/asset/uploadItem.js
I know everyone loves small documentation edits 😄. There was some confusion in [discord](https://discord.com/channels/797610307928326194/842966507826970624/960895145971167322) due to this not having an await in the JSDoc example. Adding that to prevent that.
> Adding await to uploadItem to JSDoc function example

- lib/chat/onNewConversation.js
- lib/chat/onNewMessage.js
- lib/chat/onNewMessageBySelf.js
- lib/chat/onUserOnline.js
- lib/chat/onUserTyping.js
- lib/group/onAuditLog.js
- lib/group/onGroupTransaction.js
- lib/group/onShout.js
- lib/group/onWallPost.js
- lib/party/onPartyDeleted.js
- lib/party/onPartyInvite.js
- lib/party/onPartyJoinedGame.js
- lib/party/onPartyLeftGame.js
- lib/party/onPartySelfJoined.js
- lib/party/onPartySelfLeft.js
- lib/party/onPartyUserJoined.js
- lib/party/onPartyUserLeft.js
- lib/user/onBlurbChange.js
- lib/user/onFriendRequest.js
- lib/user/onMessage.js
- lib/user/onNotification.js
Fixes #527 
It's better practice to handle the errors, and it was throwing a lot of people off as the errors could crash applications if not handled correctly - sort of like an unhandled rejection.
> Add error handling to event docs

- lib/groups/getGroup.js
- typings/index.d.ts
- typings/jsDocs.ts
The `shout` property is null for groups that have never set a shout.
> Check for existence of shout before parsing dates

- lib/games/getUniverseInfo.js
- typings/index.d.ts
Docs originally says that getUniverseInfo() returns Promise<UniverseInformation> which was incorrect. The correct return type is Promise<UniverseInformation[]>
> Update Docs getUniverseInfo()

- lib/game/getGameRevenue.js
- test/game.test.js
- typings/index.d.ts
- typings/jsDocs.ts
This just gets the game revenue. This was not in noblox.js before so I added it in.
> Added getGameRevenue

- lib/groups/getAuditLog.js
- lib/groups/onAuditLog.js
Fixes #688 
When it was changed so that created is parsed to a date in getAuditLog, it broke onAuditLog.
We need to reset the millisecond count to 0 because Roblox does something fascinating... and varies the value on each request.
> Fix onAuditLog

- lib/groups/onAuditLog.js
Added sortOrder argument to return the newest audit logs rather than only fetching the oldest ones, resulting in nothing coming through when using onAuditLog.
Sort order default being ascending resulted in the API request only returning the first 100 or so audit logs from the group.
> Fixed onAuditLog not working

- lib/games/updateDeveloperProduct.js
- typings/index.d.ts
The endpoint currently referenced by `updateDeveloperProduct` is deprecated and responds with a HTTP 404; this change updates the method to match what is used by the website.
This introduces a breaking change since `iconImageAssetId` is no longer supported. I recommend we create a new method for updating the icon rather than nesting the request inside this method; especially since the website is now required a full FormData upload instead of creating a decal and referencing it's `assetId`.
>  Update updateDeveloperProduct function to new 'apis.' endpoint; removes iconImageAssetId parameter (needs new method call)

- lib/chat/getConversations.js
- test/chat.test.js
Currently, `getConversations()` throws the not logged in error no matter what the actual error was. Instead we should return the actual errors that Roblox returns. We should also throw in cases where one or more of the conversation IDs don't exist as to prevent any surprises.
- closes #753
At some point we should change the others as well.
> Return more information than "not logged in" for getConversations

- lib/client/onNotification.js
- lib/privatemessages/getMessages.js
- lib/privatemessages/onMessage.js
- package.json
Before when you would retrieve messages, it would use the default parameter values no matter what you put when you use the function. Ex. if you change the messageTab, pageSize, or pageNumber it would only use the default values. Therefore, I removed the undefined parameter to fix it. I also added the jar: jar back because it seems to work fine with it.
I also Fixed the onMessage event where it wouldn't get messages due to change in notification name and message type. I had to add the pageSize parameter and set it to 1 so it will get the latest message because before it was sending 25 messages at a time when the event is called which is also why I had to remove the token parameter in the getMessages file because it wouldn't let me set the pageSize.
I Fixed the onNotification issue that was …
> Removed token parameter which prevented the function from respecting custom parameter values

- lib/games/publishToTopic.js
- typings/index.d.ts
Requires user to have set their API key. The API key requires access permission `Messaging Service API` and its operation `Publish`.
Use case example:
```js
// JavaScript
const noblox = require("noblox.js")
await noblox.setAPIKey(process.env.API_KEY)
const universeId = 4283343407
const topicName = "ModerateUser"
const data = { targetUser: 123456789, staffMember: 1210019099, action: "Kick" }
await noblox.publishToTopic(universeId, topicName, data)
```
```lua
-- Roblox Luau
local MessagingService = game:GetService("MessagingService")
local HttpService = game:GetService("HttpService")
MessagingService:SubscribeAsync("ModerateUser", function(message)
-- The information passed in the JavaScript is placed into `Data` and needs to be decoded
-- Types can be used here to parse the decoded data …
```
> Added postToTopic() for MessagingService needs

- .github/workflows/npmpublish.yml
Lint check currently does not run on pull requests (until merged), it would be easier than having to remember to check manually each time.
auto should not be affected as it only publishes with a release label
> Run the linting action on pull requests

- lib/games/publishToTopic.js
- lib/util/getCurrentUser.js
Accounts that do not use English as their language have the `mobileapi/userinfo` endpoint redirected to a localized path, i.e. `https://www.roblox.com/fr/mobileapi/userinfo`; this causes a HTTP 302 response code and thus throw an error for invalid cookie.
This change allows the redirect, fixing the `setCookie` and `getCurrentUser` without introducing a breaking change.
--
This change also fixes the linting errors for [`publishToTopic.js`](https://github.com/noblox/noblox.js/assets/34300238/987f929c-d5f3-424f-9620-69d36bf0e42a)
> Fix getCurrentUser redirect error for localized languages

- lib/util/http.js
It never actually worked earlier, as `.statusMessage` was never written to by noblox or request, so it retained the default forbidden text and noblox would not store the newly received token.
> Fix CSRF auto refreshing

- lib/games/configureGamePass.js
- Use new endpoint
- Fix request dying because of non-string form values
- Don't tell Roblox it's a PNG when it isn't
Error handling could be a bit better but I'm saving that for #800
> Fix configureGamePass

- package.json
- yarn.lock
Removing some unused dependencies. I had originally hoped to deprecate all use of Cheerio, but looks like it is still needed for uploadItem.
We now use standard directly for linting.
Also bumps version to v6.0.1 to account for an old publishing error, and for the breaking changes in #824
> Remove old signalr and progress bar

- lib/develop/configureItem.js
This resolves #836 and also covers an additional error code I came across when testing.
At some point (preferably when the majority of assets have moved to the new workflow) I'll change this again to make it new-endpoint-first.
> Handle itemconfiguration error codes 37 and 40

- lib/util/apiError.js
Would resolve #800 
Draft for now because I'm not sure if I want to stop it here but I'm not sure what else to add to it (another RFC time)
> Add RobloxAPIError class

- lib/util/http.js
Roblox changed the wording of the token validation error, removing the message check entirely is the better choice since there is no guarantee that they won't do it again (and was a bad idea to begin with).
> Fix CSRF token retry

- lib/users/getUsernameHistory.js
- settings.json
Easiest way to test (requires computer that isn't garbage, and don't let it run too long)
```js
const noblox = require("noblox.js");
(async function () {
while (true) {
console.log(await noblox.getUsernameHistory(53264334));
}
})();
```
Right now it's set to a day (for the combined user id, sort order, limit, and cursor) but I am open to changing it.
> Cache results from getUsernameHistory

- lib/friends/getFollowerCount.js
- lib/friends/getFollowingCount.js
- lib/friends/getFriendCount.js
- lib/users/getPlayerInfo.js
- lib/users/getUserInfo.js
- test/users.test.js
- typings/index.d.ts
- typings/jsDocs.ts
There are three issues which this solves
- The returned response/value object was never an array to begin with and that finally stopped working at some point that I can't figure out (which is now made moot by the fact that we no longer return response objects since #840)
- We were accessing the `.body` property on the body itself since that change and I forgot to change that beforehand.
- We would throw `User does not exist` regardless of what the true error was, now the error(s) is actually logged.
EDIT: Also drops `getUsernameHistory` so people don't get ratelimited all the time.
> Fix getPlayerInfo again

- lib/util/http.js
This took an embarrassingly long time to figure out, but at some point, the response headers object stopped being case-insensitive.
It is preferable that we normalize all request headers in the http method to be lowercase (the response headers are always lowercase) so that these issues do not occur in the future by way of someone using a lowercase header name in a method.
> Normalize HTTP headers

- .github/workflows/run-tests.yml
- lib/util/http.js
Right now we cannot actually test anything requiring a cookie because of region locking (which is most of this library). My solution is to use a cloud run service with direct vpc egress (which allows us to utilize a single static ip address for all requests). This would utilize workload identity federation which avoids the need for any additional secrets (by using the oidc token provided by actions).
Some actions updates were also included (and I verified they continued to work)
> Request forwarding for CI
